### ISSUE TITLE
Error with data store

### ISSUE THREAD

**Issue by Debparna** [manikandanraji/youtubeclone-backend#3]
Upon signing up this error is thrown: index.js:92 Uncaught (in promise) TypeError: Cannot read property 'data' of undefined at authenticate (index.js:92)

**Comment by manikandanraji** [comment]
Does the error occured when you are trying to run the app locally? If you are running the app locally make sure to setup the backend first (.env variables, postgresql database). You can read the README file for more information about this.

I just made a small change now in the frontend part, so clone the repo once again and try to run it to see if the error still persists.

**Comment by manikandanraji** [comment]
Does the error occured when you are trying to run the app locally? If you
are running the app locally make sure to setup the backend first (.env
variables, postgresql database). You can read the README file for more
information about this.

I just made a small change now in the frontend part, so clone the repo once
again, setup the .env variables and try to run it to see if the error still
persists.

**Comment by Debparna** [comment]
Hi!

I have included my postgres credentials in the .env file in the backend:

JWT_SECRET=8Zz5tw0Ionm3XPZZfN0NOml3z9FMfmpgXwovR9fp6ryDIoGRM8EPHAB6iHsc0fb

JWT_EXPIRE=30d // or any reasonable value that you prefer

DATABASE_URL=postgres://dpratiher:debdeb@localhost:5432/dpratiher

but the error is this on the console:

Server started at http://localhost:5000

(node:37628) UnhandledPromiseRejectionWarning: SequelizeConnectionError:
The server does not support SSL connections

    at
/Users/dpratiher/Documents/youtube/youtubeclone-backend/node_modules/sequelize/lib/dialects/postgres/connection-manager.js:188:20

    at Connection.connectingErrorHandler
(/Users/dpratiher/Documents/youtube/youtubeclone-backend/node_modules/pg/lib/client.js:213:14)

    at Connection.emit (events.js:314:20)

    at Socket.<anonymous>
(/Users/dpratiher/Documents/youtube/youtubeclone-backend/node_modules/pg/lib/connection.js:76:21)

    at Object.onceWrapper (events.js:421:26)

    at Socket.emit (events.js:314:20)

    at addChunk (_stream_readable.js:303:12)

    at readableAddChunk (_stream_readable.js:279:9)

    at Socket.Readable.push (_stream_readable.js:218:10)

    at TCP.onStreamRead (internal/stream_base_commons.js:188:23)

(Use `node --trace-warnings ...` to show where the warning was created)

(node:37628) UnhandledPromiseRejectionWarning: Unhandled promise rejection.
This error originated either by throwing inside of an async function
without a catch block, or by rejecting a promise which was not handled with
.catch(). To terminate the node process on unhandled promise rejection, use
the CLI flag `--unhandled-rejections=strict` (see
https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection
id: 1)

(node:37628) [DEP0018] DeprecationWarning: Unhandled promise rejections are
deprecated. In the future, promise rejections that are not handled will
terminate the Node.js process with a non-zero exit code.

Not sure if this is an error just local to me or others who have tried to
run it locally have gotten it as well.

**Comment by manikandanraji** [comment]
Make these changes to the file located at src/sequelize.js

```javascript
const sequelize = new Sequelize(process.env.DATABASE_URL, {
        logging: false,
	dialect: 'postgres',
	protocol: 'postgres',
	dialectOptions: {},
  });
});
```
Also remove this line 'pg.defaults.ssl = true'
